### ISSUE TITLE
Error when AWS Org has 2 Accounts with duplicate name

### ISSUE THREAD

**Issue by RW-LGC** [aws-ia/terraform-aws-iam-identity-center#48]
I tested the SSO Module in a test AWS Orgnization which had 2 AWS Accounts with the same name, both were called Development, yet seperate accounts.

As AWS does not protect against this, it seems a rare but possible scenario. When I run `terraform plan` the issue presents itself like so;

```
│ Error: Duplicate object key
│ 
│   on .terraform/modules/aws-iam-identity-center/locals.tf line 127, in locals:
│  126:   accounts_ids_maps = {
│  127:     for idx, account in data.aws_organizations_organization.organization.accounts : account.name => account.id
│  128:     if account.status == "ACTIVE" && can(data.aws_organizations_organization.organization.accounts)
│  129:   }
│     ├────────────────
│     │ account.name is "Development"
│ 
│ Two different items produced the key "Development" in this 'for' expression. If duplicates are
│ expected, use the ellipsis (...) after the value expression to enable grouping by key.
```

Is it possible to account for this at the module level?
Regards

**Comment by oraclef2k20** [comment]
May I ask why you would use the same name?

**Comment by RW-LGC** [comment]
On this occasion it's not my decision unfortunately. There are use cases where the setting of AWS account names are outside of my control but there would still be a desire to use such a module like this.

**Comment by novekm** [comment]
Hi @RW-LGC, unfortunately this is not currently on the roadmap for the module. As shown in the error, due to the module configuration accounts with the same cause a conflict with the for loops that are used to allow for dynamic assignment and to ensure the accounts are active. As a best practice we'd recommend customers to use unique account names, however I understand this may be out of your control. 

For more context, is this a scenario where you have a multi-account environment as part of a large parent company that has say "Development" accounts for multiple subsidiary companies? Just trying to think through the reasoning behind the naming convention. Either way, if this is a use case you'd like to be supported, if you submit a PR we'd be happy to review it!

**Comment by novekm** [comment]
Not on roadmap at this time
